create table users (
    id            bigint generated by default as identity primary key,
    name          varchar(255) not null,
    email         varchar(255) not null unique,
    password_hash varchar(255) not null,
    created_at    timestamptz  not null default now()
);

create table intent_mandates (
    id                       bigint generated by default as identity primary key,
    user_id                  bigint        not null references users (id),
    category                 varchar(64)   not null,
    per_order_cap            numeric(12, 2) not null,
    monthly_cap              numeric(12, 2) not null,
    escalation_threshold_pct numeric(5, 2) not null default 90,
    issued_at                timestamptz   not null default now(),
    expires_at               timestamptz   not null,
    status                   varchar(16)   not null,
    mandate_hash             varchar(64)   not null,
    created_at               timestamptz   not null default now()
);

create unique index one_active_mandate_per_user
    on intent_mandates (user_id)
    where status = 'ACTIVE';

create table catalog (
    id           bigint generated by default as identity primary key,
    name         varchar(255)   not null,
    category     varchar(64)    not null,
    price        numeric(12, 2) not null,
    stock_status varchar(16)    not null,
    description  text
);

create table cart_mandates (
    id                bigint generated by default as identity primary key,
    user_id           bigint         not null references users (id),
    intent_mandate_id bigint         not null references intent_mandates (id),
    idempotency_key   varchar(128) unique,
    cart_items        jsonb          not null,
    total_amount      numeric(12, 2) not null,
    status            varchar(24)    not null,
    rejection_reason  varchar(255),
    cart_hash         varchar(64)    not null,
    created_at        timestamptz    not null default now()
);

create index cart_mandates_user_idx on cart_mandates (user_id, id);

create table payment_mandates (
    id                bigint generated by default as identity primary key,
    user_id           bigint         not null references users (id),
    cart_mandate_id   bigint         not null unique references cart_mandates (id),
    idempotency_key   varchar(128) unique,
    razorpay_order_id varchar(128)   not null,
    amount            numeric(12, 2) not null,
    payment_status    varchar(16)    not null,
    paid_at           timestamptz,
    payment_hash      varchar(64)    not null,
    created_at        timestamptz    not null default now()
);

create table audit_log (
    id              bigint generated by default as identity primary key,
    user_id         bigint      not null references users (id),
    type            varchar(24) not null,
    reference_id    bigint      not null,
    event           varchar(24) not null,
    reason          varchar(255),
    record_snapshot text        not null,
    data_hash       varchar(64) not null,
    prev_hash       varchar(64),
    created_at      timestamptz not null default now()
);

create index audit_log_user_idx on audit_log (user_id, id);

create table restock_list (
    id          bigint generated by default as identity primary key,
    user_id     bigint      not null references users (id),
    catalog_id  bigint      not null references catalog (id),
    added_at    timestamptz not null default now(),
    consumed_at timestamptz
);

create unique index restock_open_unique
    on restock_list (user_id, catalog_id)
    where consumed_at is null;

create table agent_runs (
    id                  bigint generated by default as identity primary key,
    user_id             bigint      not null references users (id),
    intent_mandate_id   bigint      not null references intent_mandates (id),
    restock_snapshot    jsonb       not null,
    prompt              text        not null,
    raw_response        text        not null,
    parsed_cart         jsonb,
    flagged_catalog_ids jsonb,
    cart_mandate_id     bigint references cart_mandates (id),
    created_at          timestamptz not null default now()
);
